### ISSUE TITLE
possible EM update for prior_variance in  SER

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#10]
I think there should be an EM update for this - could try that instead of uniroot (should be faster each iteration)

**Comment by gaow** [comment]
@stephens999 we (@liangyy and I) looked at this data-set:

[ENSG00000232112.tar.gz](https://github.com/stephenslab/susieR/files/2161001/ENSG00000232112.tar.gz)

The z-score looks like:

```r
dat = readRDS('ENSG00000232112.rds')
res1 = susieR:::univariate_regression(dat$X, dat$y)
z = res1$betahat / res1$sebetahat
plot(z)
```

![2018-07-03-15-55-24_scrot](https://user-images.githubusercontent.com/917985/42244171-87c25cd0-7ed9-11e8-9c46-772e658df562.png)

If we perform single effect regression we get these BF with prior variance set to 0.1:

```r
res2 = susieR:::single_effect_regression(dat$y, dat$X, sa2 = 0.1, s2 = var(dat$y))
plot(exp(res2$lbf))
```

![2018-07-03-15-56-51_scrot](https://user-images.githubusercontent.com/917985/42244207-b6a08af4-7ed9-11e8-92e8-b42da3ffda47.png)

which did not reflect the trend in z-score. But apparently `sa2` was set to large for this case and changing it to 0.01 we got:

```
res2 = susieR:::single_effect_regression(dat$y, dat$X, sa2 = 0.01, s2 = var(dat$y))
plot(exp(res2$lbf))
```

![2018-07-03-15-58-49_scrot](https://user-images.githubusercontent.com/917985/42244269-fe402d2e-7ed9-11e8-9f41-e9b6c9a7a37b.png)

We really hoped that the update for prior variance will help. However if we turn on `optimize_sa2`, the uniroot function gives `V=0` thus `sa2=0`. 

So I've got 2 questions:

1. Is this a valid case to argue that choice of prior variance is still relevant (as opposed to what we show in the DSC benchmark that it does not change the results in high-signal setting), or it is not relevant because the signal is weak to start with, and we are not keen on properly doing inference for this anyways?
2. uniroot gives `sa2=0` is not desired behavior -- should we fix it, and what'd be the proper fix?

BTW applying different priors in `susie` function the objective function indeed gets larger when we set `sa` to very small numbers.

**Comment by gaow** [comment]
Actually `loglik.grad` gives negative value

```r
susieR:::loglik.grad(0, dat$y, dat$X,  var(dat$y))
```

```
-217.44575967595
```

which has led to `sa2=0`.

**Comment by stephens999** [comment]
the results suggest this example is more consistent with null than signal. Indeed, that is exactly what
the estimate that sa2=0 is telling you. And a maximum BF of 3 is telling you a similar thing I think. 
So I do not see what is wrong...

.. except that it is true that a Z score of 3+ might be expected to give a BF >3...
that might be worth looking into.

**Comment by stephens999** [comment]
so looking closer, you are running single_effect_regression on uncentered X and y ...

They need centering for it to make sense (ie basically equivalent to including an intercept).

**Comment by gaow** [comment]
> so looking closer, you are running single_effect_regression on uncentered X and y ...

Indeed. That has to be fixed ...

>  the results suggest this example is more consistent with null than signal. Indeed, that is exactly what
the estimate that sa2=0 is telling you. And a maximum BF of 3 is telling you a similar thing I think.

Yes indeed, but I was expecting to see a very small `sa2`, not `sa2=0`. Because with `sa2=0` the ranking of BF (will be 1 for all SNPs) is no longer comparable with ranking of z-scores. This is what I was wondering: is it true that for near null case, ranking of BF is no longer relevant and there is nothing to worry about its consistency with z-score rankings?

**Comment by stephens999** [comment]
much of the inconsistency is due to not using centered data
