### ISSUE TITLE
How to deal with the "." in the vcf file?

### ISSUE THREAD

**Issue by YuhaoDoong** [stephenslab/susieR#230]
When "0|0", "0|1", and "1|1" are transformed into 0, 1, and 2, then how to deal with the "." in the vcf file?

as susie function can not allow NA in the input X

**Comment by pcarbo** [comment]
@YuhaoDoong You are correct that susie does not allow missing values (NAs). If you have a very small number of missing values (say, <1%), I think it would be safe to set the missing values to the column mean. Otherwise, you will have to look into imputing the genotypes. I'm not current on the latest methods for doing this, so you will have to do some research to determine the method that is most suitable for your experimental setup.
