### ISSUE TITLE
Do not create .Rd files for functions that are not exported

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/susieR#42]
Alternatively, organize them into only a few .RD files and make clear that these are "internal" functions, and should only be used by developers or more experienced users.

`single_effect_regression` is an example of a function where you might want a nice help page (indicating at the top that this is an internal function), but I'm not sure you need a help page for `compute_Xb`, for example.

**Comment by gaow** [comment]
@pcarbo i cleaned up most of those functions but intentionally left in the sparse matrix operation related, just in case it becomes useful exploring sparse data using related approaches (same reason I left `single_effect_regression` in one of the RD files). I think it is a judgement call. It might help indicating they are internal functions. But there must be a standard R way to do it rather than inventing our own conventions?

**Comment by pcarbo** [comment]
@gaow Add a description similar to `help(.lm.fit)`, and see [here](https://stat.ethz.ch/pipermail/r-help/2004-May/051542.html) for guidance.

**Comment by gaow** [comment]
In fact there indeed is a solution in roxygen: https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html

```
@keyword internal
```

should generate the intended Rd file as you pointed out above.

**Comment by pcarbo** [comment]
@gaow Well, that is a partial solution. But note it is `@keywords internal`.

**Comment by pcarbo** [comment]
@gaow Also, you could, for example, documented all the `sparse_multiplication.R` inside one `.Rd` file, which seems like a logical organization. See [here](http://r-pkgs.had.co.nz/man.html) for instructions on how to do this using the `@rdname` tag, which seems like the best approach in this case.
