### ISSUE TITLE
default for purity

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#57]
I think we should use r^2 0.8 as the default 

first, that is a more usual default for "high" correlation in association analysis

second i think it is more appropriate for general use. 
Any default will be subjective, but the current default is very low IMO.

**Comment by stephens999** [comment]
Further thought on this, I think my suggestion was misguided. It is better to have a lower threshold, so we don't remove something that is of potential interest, and let the user decide having been presented the results. 

However I don't think we should justify the current choice as a widely used threshold

**Comment by gaow** [comment]
Oh great! Yes indeed default threshold is subjective, but I also believed that lower threshold is better. Was reluctant to change to r^2 0.8 (r 0.9) because it feels a bit too high.

> However I don't think we should justify the current choice as a widely used threshold

what would you suggest then (and why)? DAP-G's suggestion is r^2 0.25 but maybe you do not think it is a good "widely used" (outside context of fine-mapping) threshold either.

**Comment by stephens999** [comment]
i'd suggest we leave default threshold as is for now and just document what
the default threshold is. no need to say it is widely used.

**Comment by stephens999** [comment]
fixed by changing documentation
