### ISSUE TITLE
coverage in susie_get_CS

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#69]
maybe we should return the claimed coverage (which may be > threshold) rather than the requested coverage?

**Comment by gaow** [comment]
Well, it might not harm to keep it. A possible scenario is that sometimes we request a high coverage that can only be satisfied at the cost of purity -- that is we have a large CS with low purity. If the purity is too low it will get filtered out, leaving empty CS output (in other words SuSiE finds nothing). It would be less confusing to report requested coverage along with an empty results, compared to otherwise.
