### ISSUE TITLE
Effect of prior_weights on PIP

### ISSUE THREAD

**Issue by jeales** [stephenslab/susieR#83]
Hello,
I've been running `susie_bhat` on some of our eQTL results
I've been supplying posterior probabilities, based on various annotations for each SNP to the `prior_weights` argument. i.e. if the SNP has annotations correlated with greater influence on gene expression then it receives a high posterior prob and this goes straight into `prior_weights`
However I've noticed the use of `prior_weights` makes the interpretation of susie PIP values more complex.
Without using `prior_weights` I observed that the sum of PIP is ~= to the value of `L`.
This is not true when `prior_weights` are supplied and susie is returning multiple SNPs with PIP > 0.5 when L=10.

**Comment by gaow** [comment]
@jeales thanks for the report. Would you mind sharing with us here a reproducible example (saved to an R object) and the code to reproduce the behavior for us to take a look at?

**Comment by xqwen** [comment]
Hi,

We also came across this issue when comparing susie and dap-g. Currently, regardless of the simulation scenario (i.e. even under the null), we found the posterior expected number of signals, i.e., ``sum(fitted$pip)`` is always ``~L`` .  We tried to adjust prior_weights, but it did not have a noticeable effect. 

Is ``L`` dictating prior (and posterior) probabilities by design? (We are happy to share examples, but I think you should be able to reproduce this from the distributed sample code easily.)

**Comment by gaow** [comment]
@jeales to follow up on the issue, we suspect that your `prior_weights` does not sum to one, as specified in SuSiE model (the `prior_weights` applies to each single effect, a one-hot vector in SuSiE model). Failing to do so will lead to different interpretation of results, which I previously thought might be desirable at users' discretion. But clearly it is causing confusions. We have now changed the code to ensure it sums to one internally. Please update the package and let us know how it works.

@xqwen Hi there! The issue you mentioned is a discussion we had earlier:

https://github.com/stephenslab/susieR/issues/76

And in fact, even long before that thread when @stephens999 and I have discussed off-line on it and decide to do what we are doing now. In brief, this is by design, as it is consistent with the SuSiE model specification. However if you estimate prior variance (different from the current "default" SuSiE model) the story will be different. See examples below:

```
> susieR::susie(matrix(rnorm(500 * 5), nrow=500), rnorm(500), L=5)$pip
[1] 0.6372167 0.6216630 0.6275527 0.7638080 0.6919719
> susieR::susie(matrix(rnorm(500 * 5), nrow=500), rnorm(500), L=5, estimate_prior_variance=T)$pip
[1] 0 0 0 0 0
```

(which is also used in the aforementioned ticket if you are interested in reading it through).

We have recently been discussing of making `estimate_prior_effect = TRUE` the default SuSiE model. We will follow up on this thread and update the software if it happens.

**Comment by stephens999** [comment]
Yes, by default Susie fixes number of effects at exactly L. Most inferences
are robust to overstating L. In particular the number of mappable effects
(as determined by number of reported CS after purity filter)
Is robust to this.

If you really want to estimate number of effects then you need to set
estimate_prior_variance= true

**Comment by gaow** [comment]
@jeales @xqwen we have just updated `susieR` to version 0.7.0:

https://github.com/stephenslab/susieR/releases/tag/0.7.0

With this version you should see sum of PIP < L when you over specify L. 

I'll consider this issue resolved for now -- please reopen and comment if you have follow up discussions that requires our action.
